version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: syte
      MONGO_INITDB_ROOT_PASSWORD: password

  # client:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   restart: on-failure

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    
    depends_on:
      - mongodb

    volumes:
      - ./server:/home/node/app
      -  /home/node/app/node_modules
